#include <btrfsbackup/profile_render.hpp>

#include <sstream>
#include <string>
#include <vector>

namespace btrfsbackup {

namespace {

std::string shell_quote(const std::string& value) {
    if (value.empty()) {
        return "''";
    }
    if (value.find_first_not_of("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_@%+=:,./-") == std::string::npos) {
        return value;
    }
    std::string result = "'";
    for (char ch : value) {
        if (ch == '\'') {
            result += "'\"'\"'";
        } else {
            result += ch;
        }
    }
    result += "'";
    return result;
}

std::string assignment(const std::string& name, const std::string& value) {
    return name + "=" + shell_quote(value) + "\n";
}

std::string assignment(const std::string& name, const char* value) {
    return assignment(name, std::string(value));
}

std::string assignment(const std::string& name, bool value) {
    return name + "=" + std::string(value ? "true" : "false") + "\n";
}

std::string assignment(const std::string& name, long long value) {
    return name + "=" + std::to_string(value) + "\n";
}

ProfileSource source_from_json(const Json& source) {
    return {
        .id = source.at("id").get<std::string>(),
        .name = source.at("name").get<std::string>(),
        .enabled = source.at("enabled").get<bool>(),
        .subvolume = source.at("subvolume").get<std::string>(),
        .local_snapshot_dir = source.at("localSnapshotDir").get<std::string>(),
        .remote_subdir = source.at("remoteSubdir").get<std::string>(),
        .remote_retention = source.at("remoteRetention").get<long long>(),
        .local_retention = source.at("localRetention").get<long long>(),
    };
}

} // namespace

std::string render_profile_env(const Profile& profile) {
    std::string out = "# Generated by btrfs-backup-profile. Manual changes may be overwritten.\n";
    out += assignment("PROFILE_ID", profile.id);
    out += assignment("PROFILE_NAME", profile.name);
    out += assignment("BACKUP_MAPPER_NAME", profile.target.mapper_name);
    out += assignment("BACKUP_DEVICE", profile.target.device);
    out += assignment("BACKUP_LUKS_UUID", profile.target.luks_uuid);
    out += assignment("BACKUP_BTRFS_UUID", profile.target.btrfs_uuid);
    out += assignment("BACKUP_MOUNTPOINT", profile.target.mount_point);
    out += assignment("BACKUP_MOUNT_UNIT", profile.target.mount_unit);
    out += assignment("BACKUP_SERVICE_NAME", "btrfs-backup@" + profile.id + ".service");
    out += assignment("SOURCES_DIR", profile.paths.sources_dir);
    out += assignment("REMOTE_ROOT", profile.paths.remote_root);
    out += assignment("INCOMING_ROOT", profile.paths.incoming_root);
    out += assignment("RETENTION_COUNT", profile.settings.remote_retention);
    out += assignment("LOCAL_RETENTION_COUNT", profile.settings.local_retention);
    out += assignment("DAILY_LIMIT", profile.settings.daily_limit);
    out += assignment("INCREMENTAL_REQUIRED", profile.settings.incremental_required);
    out += assignment("KEEP_FAILED_LOCAL_SNAPSHOT", profile.settings.keep_failed_local_snapshot);
    out += assignment("AUTO_EJECT", profile.settings.auto_eject);
    out += assignment("MIN_TARGET_FREE_BYTES", profile.settings.minimum_target_free_bytes);
    out += assignment("MIN_LOCAL_FREE_BYTES", profile.settings.minimum_local_free_bytes);
    out += assignment("LOCK_FILE", "/run/btrfs-backup/" + profile.id + ".lock");
    out += assignment("STATE_DIR", profile.paths.state_dir);
    out += assignment("STATUS_ROOT", profile.paths.status_root);
    out += assignment("HISTORY_ROOT", profile.paths.history_root);
    out += assignment("EJECT_SCRIPT_PATH", "/usr/lib/btrfs-backup/btrfs-backup-eject.sh");
    out += assignment("NOTIFY_ENABLE", profile.notifications.enabled);
    out += assignment("NOTIFY_USER", profile.notifications.user);
    out += assignment("NOTIFY_METHOD", profile.notifications.method);
    return out;
}

std::string render_profile_env(const Json& profile) {
    return render_profile_env(profile_from_json(profile));
}

std::string render_source(const ProfileSource& source) {
    std::string out = "# Generated by btrfs-backup-profile.\n";
    out += assignment("ENABLED", source.enabled);
    out += assignment("SOURCE_NAME", source.id);
    out += assignment("SOURCE_DISPLAY_NAME", source.name);
    out += assignment("SOURCE_SUBVOLUME", source.subvolume);
    out += assignment("LOCAL_SNAPSHOT_DIR", source.local_snapshot_dir);
    out += assignment("REMOTE_SUBDIR", source.remote_subdir);
    out += assignment("SOURCE_RETENTION_COUNT", source.remote_retention);
    out += assignment("SOURCE_LOCAL_RETENTION_COUNT", source.local_retention);
    return out;
}

std::string render_source(const Json& source) {
    return render_source(source_from_json(source));
}

std::string render_udev(const Profile& profile) {
    if (!profile.enabled) {
        return "# Profile disabled; no automatic activation rule.\n";
    }
    std::vector<std::string> matches{
        "ACTION==\"add\"",
        "SUBSYSTEM==\"block\"",
        "ENV{ID_FS_TYPE}==\"crypto_LUKS\"",
        "ENV{ID_FS_UUID}==\"" + profile.target.luks_uuid + "\""
    };
    if (!profile.target.partition_uuid.empty()) {
        matches.push_back("ENV{ID_PART_ENTRY_UUID}==\"" + profile.target.partition_uuid + "\"");
    }
    if (!profile.target.serial.empty()) {
        matches.push_back("ENV{ID_SERIAL_SHORT}==\"" + profile.target.serial + "\"");
    }
    matches.push_back("TAG+=\"systemd\"");
    matches.push_back("ENV{SYSTEMD_WANTS}+=\"btrfs-backup@" + profile.id + ".service\"");
    std::ostringstream out;
    out << "# Generated by btrfs-backup-profile.\n";
    for (std::size_t i = 0; i < matches.size(); ++i) {
        if (i > 0) {
            out << ", ";
        }
        out << matches[i];
    }
    out << "\n";
    return out.str();
}

std::string render_udev(const Json& profile) {
    return render_udev(profile_from_json(profile));
}

} // namespace btrfsbackup
