#include <btrfsbackup/profile_render.hpp>

#include <sstream>
#include <utility>
#include <vector>

namespace btrfsbackup {

namespace {

std::string shell_quote(const std::string& value) {
    if (value.empty()) {
        return "''";
    }
    if (value.find_first_not_of("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_@%+=:,./-") == std::string::npos) {
        return value;
    }
    std::string result = "'";
    for (char ch : value) {
        if (ch == '\'') {
            result += "'\"'\"'";
        } else {
            result += ch;
        }
    }
    result += "'";
    return result;
}

std::string assignment(const std::string& name, const Json& value) {
    if (value.is_boolean()) {
        return name + "=" + std::string(value.get<bool>() ? "true" : "false") + "\n";
    }
    if (value.is_number_integer()) {
        return name + "=" + std::to_string(value.get<long long>()) + "\n";
    }
    return name + "=" + shell_quote(value.get<std::string>()) + "\n";
}

} // namespace

std::string render_profile_env(const Json& profile) {
    const auto& target = profile.at("target");
    const auto& paths = profile.at("paths");
    const auto& settings = profile.at("settings");
    const auto& notifications = profile.at("notifications");
    std::vector<std::pair<std::string, Json>> values{
        {"PROFILE_ID", profile.at("profileId")},
        {"PROFILE_NAME", profile.at("name")},
        {"BACKUP_MAPPER_NAME", target.at("mapperName")},
        {"BACKUP_DEVICE", target.at("device")},
        {"BACKUP_LUKS_UUID", target.at("luksUuid")},
        {"BACKUP_BTRFS_UUID", target.at("btrfsUuid")},
        {"BACKUP_MOUNTPOINT", target.at("mountPoint")},
        {"BACKUP_MOUNT_UNIT", target.at("mountUnit")},
        {"BACKUP_SERVICE_NAME", "btrfs-backup@" + profile.at("profileId").get<std::string>() + ".service"},
        {"SOURCES_DIR", paths.at("sourcesDir")},
        {"REMOTE_ROOT", paths.at("remoteRoot")},
        {"INCOMING_ROOT", paths.at("incomingRoot")},
        {"RETENTION_COUNT", settings.at("remoteRetention")},
        {"LOCAL_RETENTION_COUNT", settings.at("localRetention")},
        {"DAILY_LIMIT", settings.at("dailyLimit")},
        {"INCREMENTAL_REQUIRED", settings.at("incrementalRequired")},
        {"KEEP_FAILED_LOCAL_SNAPSHOT", settings.at("keepFailedLocalSnapshot")},
        {"AUTO_EJECT", settings.at("autoEject")},
        {"MIN_TARGET_FREE_BYTES", settings.at("minimumTargetFreeBytes")},
        {"MIN_LOCAL_FREE_BYTES", settings.at("minimumLocalFreeBytes")},
        {"LOCK_FILE", "/run/btrfs-backup/" + profile.at("profileId").get<std::string>() + ".lock"},
        {"STATE_DIR", paths.at("stateDir")},
        {"STATUS_ROOT", paths.at("statusRoot")},
        {"HISTORY_ROOT", paths.at("historyRoot")},
        {"EJECT_SCRIPT_PATH", "/usr/lib/btrfs-backup/btrfs-backup-eject.sh"},
        {"NOTIFY_ENABLE", notifications.at("enabled")},
        {"NOTIFY_USER", notifications.at("user")},
        {"NOTIFY_METHOD", notifications.at("method")}
    };
    std::string out = "# Generated by btrfs-backup-profile. Manual changes may be overwritten.\n";
    for (const auto& [key, value] : values) {
        out += assignment(key, value);
    }
    return out;
}

std::string render_source(const Json& source) {
    std::vector<std::pair<std::string, Json>> values{
        {"ENABLED", source.at("enabled")},
        {"SOURCE_NAME", source.at("id")},
        {"SOURCE_DISPLAY_NAME", source.at("name")},
        {"SOURCE_SUBVOLUME", source.at("subvolume")},
        {"LOCAL_SNAPSHOT_DIR", source.at("localSnapshotDir")},
        {"REMOTE_SUBDIR", source.at("remoteSubdir")},
        {"SOURCE_RETENTION_COUNT", source.at("remoteRetention")},
        {"SOURCE_LOCAL_RETENTION_COUNT", source.at("localRetention")}
    };
    std::string out = "# Generated by btrfs-backup-profile.\n";
    for (const auto& [key, value] : values) {
        out += assignment(key, value);
    }
    return out;
}

std::string render_udev(const Json& profile) {
    if (!profile.at("enabled").get<bool>()) {
        return "# Profile disabled; no automatic activation rule.\n";
    }
    const auto& target = profile.at("target");
    std::vector<std::string> matches{
        "ACTION==\"add\"",
        "SUBSYSTEM==\"block\"",
        "ENV{ID_FS_TYPE}==\"crypto_LUKS\"",
        "ENV{ID_FS_UUID}==\"" + target.at("luksUuid").get<std::string>() + "\""
    };
    if (!target.at("partitionUuid").get<std::string>().empty()) {
        matches.push_back("ENV{ID_PART_ENTRY_UUID}==\"" + target.at("partitionUuid").get<std::string>() + "\"");
    }
    if (!target.at("serial").get<std::string>().empty()) {
        matches.push_back("ENV{ID_SERIAL_SHORT}==\"" + target.at("serial").get<std::string>() + "\"");
    }
    matches.push_back("TAG+=\"systemd\"");
    matches.push_back("ENV{SYSTEMD_WANTS}+=\"btrfs-backup@" + profile.at("profileId").get<std::string>() + ".service\"");
    std::ostringstream out;
    out << "# Generated by btrfs-backup-profile.\n";
    for (std::size_t i = 0; i < matches.size(); ++i) {
        if (i > 0) {
            out << ", ";
        }
        out << matches[i];
    }
    out << "\n";
    return out.str();
}

} // namespace btrfsbackup
