# SPDX-FileCopyrightText: 2026 Kamil Piwowarski <kapiwko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

if(NOT DEFINED SCANNER OR NOT DEFINED COMPILE_COMMANDS OR NOT DEFINED PROBE_ROOT OR NOT DEFINED MANIFEST)
    message(FATAL_ERROR "SCANNER, COMPILE_COMMANDS, PROBE_ROOT, and MANIFEST are required")
endif()
include("${MANIFEST}")

function(public_dependency_reachable start sought result_variable)
    set(queue "${start}")
    set(visited)
    set(found FALSE)
    while(queue AND NOT found)
        list(POP_FRONT queue current)
        if(current STREQUAL sought)
            set(found TRUE)
            break()
        endif()
        if(current IN_LIST visited)
            continue()
        endif()
        list(APPEND visited "${current}")
        if(current MATCHES "^btrfsbackup-")
            list(APPEND queue ${BTRFSBACKUP_PUBLIC_DEPS_${current}})
        endif()
    endwhile()
    set(${result_variable} ${found} PARENT_SCOPE)
endfunction()

file(READ "${COMPILE_COMMANDS}" compilation_database)
string(JSON command_count LENGTH "${compilation_database}")
set(filtered_database "[]")
set(filtered_count 0)
if(command_count GREATER 0)
    math(EXPR last_command "${command_count} - 1")
    foreach(index RANGE ${last_command})
        string(JSON source_file GET "${compilation_database}" ${index} file)
        cmake_path(IS_PREFIX PROBE_ROOT "${source_file}" NORMALIZE is_header_probe)
        if(is_header_probe)
            string(JSON command_entry GET "${compilation_database}" ${index})
            string(JSON filtered_database SET "${filtered_database}" ${filtered_count} "${command_entry}")
            math(EXPR filtered_count "${filtered_count} + 1")
        endif()
    endforeach()
endif()
if(filtered_count EQUAL 0)
    message(FATAL_ERROR "compilation database contains no public header probes under ${PROBE_ROOT}")
endif()

set(filtered_path "${PROBE_ROOT}/compile_commands.json")
file(WRITE "${filtered_path}" "${filtered_database}")
execute_process(
    COMMAND "${SCANNER}" -compilation-database=${filtered_path} -format=make
    RESULT_VARIABLE scan_result
    OUTPUT_VARIABLE scan_output
    ERROR_VARIABLE scan_error
)
if(NOT scan_result EQUAL 0)
    message(FATAL_ERROR "clang-scan-deps failed:\n${scan_error}")
endif()

string(REPLACE "\n" ";" scan_lines "${scan_output}")
unset(current_target)
foreach(line IN LISTS scan_lines)
    if(line MATCHES "^CMakeFiles/(btrfsbackup-[A-Za-z0-9-]+)-public-header-probe\\.dir/")
        set(current_target "${CMAKE_MATCH_1}")
    endif()
    if(DEFINED current_target)
        string(APPEND "target_scan_${current_target}" "${line}\n")
    endif()
endforeach()

set(unused_public_dependencies)
set(transitively_redundant_dependencies)
foreach(target IN LISTS BTRFSBACKUP_ARCHITECTURE_TARGETS)
    set(target_scan "${target_scan_${target}}")
    if(NOT target_scan)
        continue()
    endif()
    set(public_dependencies "${BTRFSBACKUP_PUBLIC_DEPS_${target}}")
    foreach(dependency IN LISTS public_dependencies)
        if(NOT dependency MATCHES "^btrfsbackup-")
            continue()
        endif()
        foreach(other_dependency IN LISTS public_dependencies)
            if(other_dependency STREQUAL dependency)
                continue()
            endif()
            public_dependency_reachable("${other_dependency}" "${dependency}" reachable_transitively)
            if(reachable_transitively)
                list(APPEND transitively_redundant_dependencies
                    "${target} -> ${dependency} (already exposed by ${other_dependency})"
                )
                break()
            endif()
        endforeach()
        set(dependency_headers "${BTRFSBACKUP_HEADERS_${dependency}}")
        if(NOT dependency_headers)
            continue()
        endif()
        set(dependency_used FALSE)
        foreach(header IN LISTS dependency_headers)
            string(FIND "${target_scan}" "${header}" header_position)
            if(NOT header_position EQUAL -1)
                set(dependency_used TRUE)
                break()
            endif()
        endforeach()
        if(NOT dependency_used)
            list(APPEND unused_public_dependencies "${target} -> ${dependency}")
        endif()
    endforeach()
endforeach()

if(unused_public_dependencies OR transitively_redundant_dependencies)
    list(JOIN unused_public_dependencies "\n  " formatted_dependencies)
    list(JOIN transitively_redundant_dependencies "\n  " formatted_redundant_dependencies)
    message(
        FATAL_ERROR
        "PUBLIC dependencies unused by public headers according to clang-scan-deps:\n"
        "  ${formatted_dependencies}\n"
        "Transitively redundant direct PUBLIC dependencies:\n"
        "  ${formatted_redundant_dependencies}"
    )
endif()
