// SPDX-FileCopyrightText: 2026 Kamil Piwowarski <kapiwko@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

#include <config/ProfileRender.hpp>

#include <cctype>
#include <cstddef>
#include <sstream>
#include <string>
#include <vector>

#include <config/domain/Profile.hpp>

namespace btrfsbackup::config {

namespace {

std::string systemd_quote(const std::string& value) {
    std::string result = "\"";
    for (char ch : value) {
        if (ch == '\\' || ch == '"') {
            result.push_back('\\');
        }
        result.push_back(ch);
    }
    result.push_back('"');
    return result;
}

bool systemd_unit_plain_char(unsigned char value) {
    return std::isalnum(value) || value == ':' || value == '_' || value == '.';
}

std::string systemd_hex_escape(unsigned char value) {
    constexpr char digits[] = "0123456789abcdef";
    std::string result = "\\x";
    result.push_back(digits[(value >> 4U) & 0x0fU]);
    result.push_back(digits[value & 0x0fU]);
    return result;
}

std::string udev_value(const std::string& value) {
    std::string result;
    for (const unsigned char character : value) {
        if (character == '"' || character == '\\' || character < 0x20 || character == 0x7f) {
            result += systemd_hex_escape(character);
        } else {
            result.push_back(static_cast<char>(character));
        }
    }
    return result;
}

} // namespace

std::string render_udev(const Profile& profile) {
    const std::string generation = profile.configuration_generation.empty()
        ? ""
        : "# Configuration generation: " + profile.configuration_generation.value() + "\n";
    std::vector<std::string> matches{
        "ACTION==\"add\"",
        "SUBSYSTEM==\"block\"",
        "ENV{ID_FS_TYPE}==\"crypto_LUKS\"",
        "ENV{ID_FS_UUID}==\"" + profile.target.luks_uuid.value() + "\""
    };
    if (!profile.target.partition_uuid.empty()) {
        matches.push_back("ENV{ID_PART_ENTRY_UUID}==\"" + profile.target.partition_uuid.value() + "\"");
    }
    if (!profile.target.serial.empty()) {
        matches.push_back("ENV{ID_SERIAL_SHORT}==\"" + profile.target.serial + "\"");
    }
    matches.push_back("ENV{UDISKS_NAME}=\"" + udev_value(profile.name) + "\"");
    matches.push_back("ENV{UDISKS_ICON_NAME}=\"drive-removable-media\"");
    matches.push_back("ENV{UDISKS_SYSTEM}=\"0\"");
    matches.push_back("ENV{UDISKS_IGNORE}=\"0\"");
    if (profile.enabled) {
        matches.push_back("TAG+=\"systemd\"");
        matches.push_back("ENV{SYSTEMD_WANTS}+=\"btrfs-backup@" + std::string(profile.id.value()) + ".service\"");
    }
    std::ostringstream out;
    out << "# Generated by btrfs-backupctl profile.\n"
        << generation;
    if (!profile.enabled)
        out << "# Profile disabled; automatic activation is not requested.\n";
    for (std::size_t i = 0; i < matches.size(); ++i) {
        if (i > 0) {
            out << ", ";
        }
        out << matches[i];
    }
    out << "\n";
    return out.str();
}

std::string render_mount_requirement(const Profile& profile) {
    return "RequiresMountsFor=" + systemd_quote(profile.target.mount_point.value().string()) + "\n";
}

std::string render_mount_dependency(const Profile& profile) {
    std::string result = "[Unit]\n" + render_mount_requirement(profile);
    if (!profile.configuration_generation.empty()) {
        result += "\n[Service]\nEnvironment=BTRFS_BACKUP_CONFIGURATION_GENERATION=" + profile.configuration_generation.value() + "\n";
    }
    return result;
}

std::string target_mount_unit_name(const std::filesystem::path& mount_point) {
    std::string path = mount_point.lexically_normal().string();
    while (path.size() > 1 && path.back() == '/') {
        path.pop_back();
    }
    if (path == "/") {
        return "-.mount";
    }
    if (!path.empty() && path.front() == '/') {
        path.erase(path.begin());
    }

    std::string escaped;
    bool previous_slash = false;
    for (const char character : path) {
        const auto value = static_cast<unsigned char>(character);
        if (value == '/') {
            if (!escaped.empty() && !previous_slash) {
                escaped.push_back('-');
            }
            previous_slash = true;
            continue;
        }
        previous_slash = false;
        escaped += systemd_unit_plain_char(value) ? std::string(1, character) : systemd_hex_escape(value);
    }
    return (escaped.empty() ? "-" : escaped) + ".mount";
}

std::string target_device_unit_name(const std::filesystem::path& device) {
    std::string path = device.lexically_normal().string();
    if (!path.empty() && path.front() == '/') {
        path.erase(path.begin());
    }

    std::string escaped;
    for (const char character : path) {
        const auto value = static_cast<unsigned char>(character);
        if (value == '/') {
            escaped.push_back('-');
        } else {
            escaped += systemd_unit_plain_char(value) ? std::string(1, character) : systemd_hex_escape(value);
        }
    }
    return (escaped.empty() ? "-" : escaped) + ".device";
}

std::string render_target_mount_unit(const Profile& profile) {
    const std::string profile_id{profile.id.value()};
    const std::string device_unit = target_device_unit_name(profile.target.device);
    return "[Unit]\n"
           "Description=Encrypted Btrfs backup target for profile " +
        profile_id +
        "\n"
        "Documentation=file:/usr/share/doc/btrfs-backup/README.md\n"
        "BindsTo=" +
        device_unit +
        "\n"
        "Requires=btrfs-backup-target@" +
        profile_id +
        ".service\n"
        "After=" +
        device_unit +
        "\n"
        "After=btrfs-backup-target@" +
        profile_id +
        ".service\n"
        "Before=btrfs-backup@" +
        profile_id +
        ".service\n"
        "\n"
        "[Mount]\n"
        "What=/dev/mapper/" +
        profile.target.mapper_name.value() +
        "\n"
        "Where=" +
        profile.target.mount_point.value().string() +
        "\n"
        "Type=btrfs\n"
        "Options=noatime,nodev,nosuid,noexec,nosymfollow,compress=zstd\n"
        "TimeoutSec=60s\n";
}

} // namespace btrfsbackup::config
