// SPDX-FileCopyrightText: 2026 Kamil Piwowarski <kapiwko@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

#include <config/profile_render.hpp>

#include <cstddef>
#include <sstream>
#include <string>
#include <vector>

#include <config/profile.hpp>

namespace btrfsbackup {

namespace {

std::string systemd_quote(const std::string& value) {
    std::string result = "\"";
    for (char ch : value) {
        if (ch == '\\' || ch == '"') {
            result.push_back('\\');
        }
        result.push_back(ch);
    }
    result.push_back('"');
    return result;
}

} // namespace

std::string render_udev(const Profile& profile) {
    const std::string generation = profile.configuration_generation.empty()
        ? ""
        : "# Configuration generation: " + profile.configuration_generation + "\n";
    if (!profile.enabled) {
        return generation + "# Profile disabled; no automatic activation rule.\n";
    }
    std::vector<std::string> matches{
        "ACTION==\"add\"",
        "SUBSYSTEM==\"block\"",
        "ENV{ID_FS_TYPE}==\"crypto_LUKS\"",
        "ENV{ID_FS_UUID}==\"" + profile.target.luks_uuid + "\""
    };
    if (!profile.target.partition_uuid.empty()) {
        matches.push_back("ENV{ID_PART_ENTRY_UUID}==\"" + profile.target.partition_uuid + "\"");
    }
    if (!profile.target.serial.empty()) {
        matches.push_back("ENV{ID_SERIAL_SHORT}==\"" + profile.target.serial + "\"");
    }
    matches.push_back("TAG+=\"systemd\"");
    matches.push_back("ENV{SYSTEMD_WANTS}+=\"btrfs-backup@" + profile.id + ".service\"");
    std::ostringstream out;
    out << "# Generated by btrfs-backupctl profile.\n" << generation;
    for (std::size_t i = 0; i < matches.size(); ++i) {
        if (i > 0) {
            out << ", ";
        }
        out << matches[i];
    }
    out << "\n";
    return out.str();
}

std::string render_mount_requirement(const Profile& profile) {
    return "RequiresMountsFor=" + systemd_quote(profile.target.mount_point) + "\n";
}

std::string render_mount_dependency(const Profile& profile) {
    std::string result = "[Unit]\n" + render_mount_requirement(profile);
    if (!profile.configuration_generation.empty()) {
        result += "\n[Service]\nEnvironment=BTRFS_BACKUP_CONFIGURATION_GENERATION="
            + profile.configuration_generation + "\n";
    }
    return result;
}

} // namespace btrfsbackup
