// SPDX-FileCopyrightText: 2026 Kamil Piwowarski <kapiwko@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

#include <filesystem>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

#include <backup/model/snapshot_inventory.hpp>

#include "support/validation_test_helpers.hpp"

namespace fs = std::filesystem;

namespace {

void test_parse_snapshot_name() {
    std::optional<btrfsbackup::backup::SnapshotName> parsed =
        btrfsbackup::backup::parse_snapshot_name("home-2026-08-23T082504Z", "home");

    test_helpers::expect_true("parse snapshot name", parsed.has_value(), "expected snapshot name to parse");
    test_helpers::expect_eq("parse source", parsed->source_id, "home");
    test_helpers::expect_eq("parse timestamp", parsed->timestamp, "2026-08-23T082504Z");
    test_helpers::expect_eq("parse sequence", std::to_string(parsed->sequence), "0");

    parsed = btrfsbackup::backup::parse_snapshot_name("home-2026-08-23T082504Z-02", "home");
    test_helpers::expect_true("parse snapshot sequence", parsed.has_value(), "expected sequence snapshot to parse");
    test_helpers::expect_eq("parse sequence value", std::to_string(parsed->sequence), "2");

    test_helpers::expect_true(
        "reject wrong source",
        !btrfsbackup::backup::parse_snapshot_name("root-2026-08-23T082504Z", "home").has_value(),
        "snapshot for another source should be ignored"
    );
    test_helpers::expect_true(
        "reject bad timestamp",
        !btrfsbackup::backup::parse_snapshot_name("home-2026-08-23-082504", "home").has_value(),
        "bad timestamp should be ignored"
    );
    test_helpers::expect_true(
        "reject zero sequence",
        !btrfsbackup::backup::parse_snapshot_name("home-2026-08-23T082504Z-00", "home").has_value(),
        "zero collision suffix is not generated by the runtime"
    );
}

void test_list_snapshot_inventory() {
    fs::path root = test_helpers::test_root("snapshot-inventory", "list");
    fs::path snapshots = root / "snapshots";
    fs::create_directories(snapshots / "home-2026-08-23T082504Z");
    fs::create_directories(snapshots / "home-2026-08-23T082504Z-01");
    fs::create_directories(snapshots / "home-2026-08-22T082504Z");
    fs::create_directories(snapshots / "root-2026-08-23T082504Z");
    fs::create_directories(snapshots / "home-not-a-snapshot");
    test_helpers::write_file(snapshots / "home-2026-08-24T082504Z", "not a directory");

    std::unordered_map<std::string, btrfsbackup::backup::SnapshotMetadata> metadata{
        {
            (snapshots / "home-2026-08-22T082504Z").string(),
            {.is_subvolume = true, .readonly = true, .uuid = "uuid-old"},
        },
        {
            (snapshots / "home-2026-08-23T082504Z").string(),
            {.is_subvolume = true, .readonly = true, .uuid = "uuid-new"},
        },
        {
            (snapshots / "home-2026-08-23T082504Z-01").string(),
            {.is_subvolume = true, .readonly = false, .uuid = "uuid-new-seq", .received_uuid = "received-new-seq"},
        },
        {
            (snapshots / "root-2026-08-23T082504Z").string(),
            {.is_subvolume = true, .readonly = true, .uuid = "uuid-root"},
        },
    };

    std::vector<btrfsbackup::backup::SnapshotInfo> inventory = btrfsbackup::backup::list_snapshot_inventory(
        snapshots,
        "home",
        btrfsbackup::backup::SnapshotSide::Local,
        [&](const fs::path& path) -> std::optional<btrfsbackup::backup::SnapshotMetadata> {
            auto found = metadata.find(path.string());
            if (found == metadata.end()) {
                return std::nullopt;
            }
            return found->second;
        }
    );

    test_helpers::expect_eq("inventory count", std::to_string(inventory.size()), "3");
    test_helpers::expect_eq("inventory sorted old", inventory.at(0).name, "home-2026-08-22T082504Z");
    test_helpers::expect_eq("inventory sorted new", inventory.at(1).name, "home-2026-08-23T082504Z");
    test_helpers::expect_eq("inventory sorted sequence", inventory.at(2).name, "home-2026-08-23T082504Z-01");
    test_helpers::expect_eq("inventory uuid", inventory.at(2).uuid, "uuid-new-seq");
    test_helpers::expect_eq("inventory received uuid", inventory.at(2).received_uuid, "received-new-seq");
    test_helpers::expect_true("inventory readonly flag", !inventory.at(2).readonly, "readonly flag should follow metadata");

    fs::remove_all(root);
}

void test_empty_and_missing_directories() {
    fs::path root = test_helpers::test_root("snapshot-inventory", "empty");

    std::vector<btrfsbackup::backup::SnapshotInfo> missing = btrfsbackup::backup::list_snapshot_inventory(
        root / "missing",
        "home",
        btrfsbackup::backup::SnapshotSide::Remote,
        [](const fs::path&) -> std::optional<btrfsbackup::backup::SnapshotMetadata> {
            return btrfsbackup::backup::SnapshotMetadata{.is_subvolume = true};
        }
    );
    test_helpers::expect_eq("missing inventory", std::to_string(missing.size()), "0");

    fs::create_directories(root / "empty");
    std::vector<btrfsbackup::backup::SnapshotInfo> empty = btrfsbackup::backup::list_snapshot_inventory(
        root / "empty",
        "home",
        btrfsbackup::backup::SnapshotSide::Remote,
        [](const fs::path&) -> std::optional<btrfsbackup::backup::SnapshotMetadata> {
            return btrfsbackup::backup::SnapshotMetadata{.is_subvolume = true};
        }
    );
    test_helpers::expect_eq("empty inventory", std::to_string(empty.size()), "0");

    fs::remove_all(root);
}

void test_inventory_separates_scan_and_reported_paths() {
    fs::path root = test_helpers::test_root("snapshot-inventory", "reported-path");
    fs::path scan = root / "fd-view";
    fs::path reported = "/mnt/backup/snapshots/home";
    fs::create_directories(scan / "home-2026-08-23T082504Z");
    fs::path metadata_path;

    std::vector<btrfsbackup::backup::SnapshotInfo> inventory = btrfsbackup::backup::list_snapshot_inventory_at(
        scan,
        reported,
        "home",
        btrfsbackup::backup::SnapshotSide::Remote,
        [&](const fs::path& path) -> std::optional<btrfsbackup::backup::SnapshotMetadata> {
            metadata_path = path;
            return btrfsbackup::backup::SnapshotMetadata{.is_subvolume = true, .readonly = true, .uuid = "uuid"};
        }
    );

    test_helpers::expect_eq("inventory metadata scan path", metadata_path.string(), (scan / "home-2026-08-23T082504Z").string());
    test_helpers::expect_eq("inventory reported path", inventory.at(0).path.string(), (reported / "home-2026-08-23T082504Z").string());
    fs::remove_all(root);
}

void test_inventory_rejects_symlink_entries() {
    fs::path root = test_helpers::test_root("snapshot-inventory", "symlink");
    fs::create_directories(root / "outside");
    fs::create_directories(root / "snapshots");
    fs::create_directory_symlink(root / "outside", root / "snapshots" / "home-2026-08-23T082504Z");

    test_helpers::expect_validation_error("inventory symlink rejected", [&] { (void)btrfsbackup::backup::list_snapshot_inventory(
                                                                                  root / "snapshots",
                                                                                  "home",
                                                                                  btrfsbackup::backup::SnapshotSide::Remote,
                                                                                  [](const fs::path&) -> std::optional<btrfsbackup::backup::SnapshotMetadata> {
                                                                                      return btrfsbackup::backup::SnapshotMetadata{.is_subvolume = true};
                                                                                  }
                                                                              ); }, "symbolic link is forbidden in snapshot inventory");
    fs::remove_all(root);
}

void test_invalid_inputs() {
    test_helpers::expect_validation_error("invalid source id", [] { (void)btrfsbackup::backup::parse_snapshot_name("bad source-2026-08-23T082504Z", "bad source"); }, "sourceId contains unsupported characters");

    test_helpers::expect_validation_error("missing metadata reader", [] { (void)btrfsbackup::backup::list_snapshot_inventory(
                                                                              "/tmp",
                                                                              "home",
                                                                              btrfsbackup::backup::SnapshotSide::Local,
                                                                              nullptr
                                                                          ); }, "snapshot metadata reader is required");
}

} // namespace

int main() {
    test_parse_snapshot_name();
    test_list_snapshot_inventory();
    test_empty_and_missing_directories();
    test_inventory_separates_scan_and_reported_paths();
    test_inventory_rejects_symlink_entries();
    test_invalid_inputs();

    return test_helpers::finish("snapshot inventory tests");
}
