# SPDX-FileCopyrightText: 2026 Kamil Piwowarski <kapiwko@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

if(NOT DEFINED SOURCE_DIR OR SOURCE_DIR STREQUAL "")
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

set(workflow "${SOURCE_DIR}/.github/workflows/release-gates.yml")
file(READ "${workflow}" contents)

function(require_text expected)
    string(FIND "${contents}" "${expected}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Release workflow is missing '${expected}'")
    endif()
endfunction()

function(require_order earlier later)
    string(FIND "${contents}" "${earlier}" earlier_position)
    string(FIND "${contents}" "${later}" later_position)
    if(earlier_position EQUAL -1 OR later_position EQUAL -1)
        message(FATAL_ERROR "Cannot compare missing release workflow steps")
    endif()
    if(NOT earlier_position LESS later_position)
        message(FATAL_ERROR "Release workflow must run '${earlier}' before '${later}'")
    endif()
endfunction()

require_text("tags:")
require_text("- \"v*.*.*\"")
require_text("name: release-artifacts-\${{ github.sha }}")
require_text("path: build/release-artifacts/")
require_text("retention-days: 90")
require_text("- packaging")
require_text("- real-btrfs")
require_text("- qemu")
require_text("Validate signed annotated release tag")
require_text(".verification.verified")
require_text("actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a")
require_text("actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c")
require_text("actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8")
require_text("gh release create")
require_text("--draft")
require_text("Verify published release assets")
require_text("sha256sum --check ../release-artifacts/SHA256SUMS")
require_text("gh release edit \"\${GITHUB_REF_NAME}\" --draft=false")

require_order("Verify release checksums" "Preserve verified release artifacts")
require_order("Download gated release artifacts" "Verify downloaded release artifacts")
require_order("Verify downloaded release artifacts" "Attest gated release artifacts")
require_order("Attest gated release artifacts" "Create draft GitHub release from gated artifacts")
require_order("Create draft GitHub release from gated artifacts" "Verify published release assets")
require_order("Verify published release assets" "Publish verified GitHub release")
